name: github-changelog-generator
version: master
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  github-changelog-generator:
    command: github_changelog_generator
    plugs: [home]

parts:
  github-changelog-generator:
    source: .
    plugin: ruby
    build: gem build github_changelog_generator.gemspec
    install: gem install github_changelog_generator-*.gem --env-shebang
    stage-packages: [git]